version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:8000"
    environment:
      - PAYMENT_SHEET=${PAYMENT_SHEET:-}
      - NOW_SHEET_SERVICE=${NOW_SHEET_SERVICE:-}
      - NOW_SHEET_ID=${NOW_SHEET_ID:-}
    # volumes:
    #   - .:/app
    # command: ["uv", "run", "uvicorn", "index:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000"] # Assuming there's a /health endpoint
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s